### ISSUE TITLE
单张图片时能不让他滚动嘛

### ISSUE THREAD

**Issue by taitanxiami** [ylovern/GGBannerView#1]
就是当只有一张图片的时候就不要让他在左右滚动了，这样可以嘛

**Comment by ylovern** [comment]
你看下参数，有一个设置自动滚动间隔时间的。把它赋值为0就不会自动滚动。

**Comment by ylovern** [comment]
自动换页时间间隔，0s 不滚动

``` objective-c
@property (nonatomic, assign) NSTimeInterval interval; // default is 0s
```

**Comment by taitanxiami** [comment]
interval这个属性挺好的，但是我现在是意思是只有一张的时候，且interval = 0，能不能就让他不随着手势滚动，因为一张图的话，就是来回滚动了（显示的就是这一张图片）

**Comment by ylovern** [comment]
明白了。 你的意思是不让他响应手势的滑动。我可以添加一个参数来开关是否响应手势。

**Comment by taitanxiami** [comment]
好的啊，这样一张图的时候就不让他来回滑动了

**Comment by ylovern** [comment]
已添加，你可以试一下

**Comment by taitanxiami** [comment]
好的，我试试，3Q
